services:
  mysql:
    image: mysql:8.0
    container_name: mysql-instagram
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_HOST_PORT}:${MYSQL_DOCKER_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
