spring:
  application:
    name: instagram

  datasource:
    driver-class-name: ${DATABASE_DRIVER:org.h2.Driver}
    url: ${DATABASE_URL:jdbc:h2:mem:core?MODE=MYSQL}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: embedded

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user


instagram:
  imgbb:
    api-key: ${IMGBB_API_KEY}
  jwt:
    issuer: ${JWT_ISSUER:team.resuscitation}
    expiration: ${JWT_EXPIRATION:1800000} # 30 minutes
    secret-key: ${JWT_SECRET_KEY:this-is-secret-key-for-instagram}

# 알파펫 순서로 정렬

springdoc:
  swagger-ui:
    tags-sorter: alpha
